// CLI-side localization (the web UI carries its own dictionary in ui.html).
// Language resolution: --lang flag > AGENTFDR_LANG > LANG/LC_ALL > 'en'.

export function resolveLang(explicit) {
  const cand = explicit ?? process.env.AGENTFDR_LANG ?? process.env.LC_ALL ?? process.env.LANG ?? '';
  return /^ja/i.test(cand) ? 'ja' : 'en';
}

const STRINGS = {
  en: {
    flightReport: 'Flight report',
    session: 'Session',
    project: 'Project',
    model: 'Model',
    started: 'Started',
    wallTime: 'Wall time',
    turns: 'Turns',
    toolCalls: 'Tool calls',
    errors: 'errors',
    tokens: 'Tokens',
    tokensLine: (t, k) => `in ${k(t.input)} / out ${k(t.output)} / cache-read ${k(t.cacheRead)} / cache-write ${k(t.cacheCreation)}`,
    estCost: 'Est. cost',
    estCostNote: '(from list prices; estimate only)',
    effortLabel: 'Effort',
    webLabel: 'Web',
    webLine: (s, f) => `search ${s} / fetch ${f}`,
    compactionLabel: 'Compaction',
    unknownModels: (m) => `Note: cost excludes unpriced model(s): ${m}`,
    anomalies: 'Anomalies',
    noAnomalies: '**No anomalies detected.** (That means the heuristics found nothing — not that nothing went wrong.)',
    turnRange: (a, b) => (a === b ? `turn ${a}` : `turns ${a}–${b}`),
    footer: (id) => `_Generated by \`agentfdr\`. Open the timeline with \`agentfdr open ${id}\`._`,
    openWith: 'Open one with: agentfdr open <id-prefix>',
    noSessions: (root) => `No sessions found under ${root}`,
    untitled: '(untitled)',
    plan: 'Plan',
    window5h: 'Current 5h window',
    noActiveWindow: 'no active window',
    today: 'Today',
    week7d: 'Last 7 days',
    windowsUsed: (n) => `${n} windows started`,
    perDay: 'Per day (billed tokens = fresh input + cache write + output):',
    perModel: 'Per model:',
    turnsN: (n) => `${n} turns`,
    usageNote:
      'Plan limits are not published and not stored locally. Calibrate --budget-5h / --budget-week against Claude Code\'s /usage screen.',
  },
  ja: {
    flightReport: 'フライトレポート',
    session: 'セッション',
    project: 'プロジェクト',
    model: 'モデル',
    started: '開始時刻',
    wallTime: '実時間',
    turns: 'ターン数',
    toolCalls: 'ツール呼び出し',
    errors: 'エラー',
    tokens: 'トークン',
    tokensLine: (t, k) => `入力 ${k(t.input)} / 出力 ${k(t.output)} / キャッシュ読取 ${k(t.cacheRead)} / キャッシュ書込 ${k(t.cacheCreation)}`,
    estCost: '推定コスト',
    estCostNote: '(定価ベースの概算)',
    effortLabel: 'effort設定',
    webLabel: 'Web',
    webLine: (s, f) => `検索 ${s} / 取得 ${f}`,
    compactionLabel: 'コンテキスト圧縮',
    unknownModels: (m) => `注: 料金不明のモデルはコストに含まれていません: ${m}`,
    anomalies: '検知された異常',
    noAnomalies: '**異常は検知されませんでした。**(ヒューリスティックが何も見つけなかっただけで、問題がなかったという意味ではありません)',
    turnRange: (a, b) => (a === b ? `ターン ${a}` : `ターン ${a}–${b}`),
    footer: (id) => `_\`agentfdr\` により生成。タイムラインを開くには \`agentfdr open ${id}\`_`,
    openWith: '開くには: agentfdr open <IDの先頭数文字>',
    noSessions: (root) => `${root} にセッションが見つかりません`,
    untitled: '(無題)',
    plan: 'プラン',
    window5h: '現在の5時間ウィンドウ',
    noActiveWindow: 'アクティブなウィンドウなし',
    today: '今日',
    week7d: '直近7日',
    windowsUsed: (n) => `ウィンドウ開始 ${n}回`,
    perDay: '日別(課金トークン = 新規入力 + キャッシュ書込 + 出力):',
    perModel: 'モデル別:',
    turnsN: (n) => `${n}ターン`,
    usageNote:
      'プランの正確な上限は非公開でローカルにも記録されません。Claude Code の /usage 画面と見比べて --budget-5h / --budget-week を調整してください。',
  },
};

export function t(lang) {
  return STRINGS[lang] ?? STRINGS.en;
}

// Flag titles/details built from structured params so every language renders
// from the same data. Falls back to the English strings detect.js embeds.
const FLAG_FMT = {
  en: {
    'loop': (p) => [`Tool loop ×${p.repeats}`, `Repeated ${p.repeats}× (${p.span} calls): ${p.gram}`],
    'error-streak': (p) => [`${p.count} consecutive tool errors`, `Starting with ${p.firstSig}`],
    'context-bloat': (p) => [`Huge tool result (${p.kchars}k chars)`, `${p.name}: ${p.summary}`],
    'token-spike': (p) => [`Context jumped +${p.deltaK}k tokens`, `${p.fromK}k → ${p.toK}k in one turn`],
    'cache-thrash': (p) => [`${p.count} turns with zero cache hits`, 'Full input re-read each turn — check for context churn'],
    'file-churn': (p) => [`Same file edited ${p.count}×`, p.path],
    'refusal': () => ['Model refusal', 'stop_reason: refusal — the request was declined'],
  },
  ja: {
    'loop': (p) => [`ツールループ ×${p.repeats}`, `同一パターンを${p.repeats}回反復(${p.span}回の呼び出し): ${p.gram}`],
    'error-streak': (p) => [`ツールエラーが${p.count}回連続`, `起点: ${p.firstSig}`],
    'context-bloat': (p) => [`巨大なツール結果(${p.kchars}k文字)`, `${p.name}: ${p.summary}`],
    'token-spike': (p) => [`コンテキストが+${p.deltaK}kトークン急増`, `1ターンで ${p.fromK}k → ${p.toK}k`],
    'cache-thrash': (p) => [`${p.count}ターン連続でキャッシュヒットなし`, `毎ターン全入力を再読込 — コンテキストの入れ替わりを確認`],
    'file-churn': (p) => [`同一ファイルを${p.count}回編集`, p.path],
    'refusal': () => ['モデルによる拒否', 'stop_reason: refusal — リクエストが拒否されました'],
  },
};

/** [title, detail] for a flag in the given language. */
export function formatFlag(flag, lang) {
  const fmt = FLAG_FMT[lang]?.[flag.type];
  if (fmt && flag.params) return fmt(flag.params);
  return [flag.title, flag.detail];
}
