// `agentfdr blame` — a paste-into-an-issue markdown autopsy of one session.

export function blameReport(model, flags) {
  const { session, totals, turns } = model;
  const lines = [];
  const kTok = (n) => (n >= 1000 ? `${Math.round(n / 1000)}k` : String(n));

  lines.push(`# Flight report: ${session.title ?? session.id ?? 'session'}`);
  lines.push('');
  lines.push(`| | |`);
  lines.push(`|---|---|`);
  if (session.id) lines.push(`| Session | \`${session.id}\` |`);
  if (session.cwd) lines.push(`| Project | \`${session.cwd}\`${session.gitBranch ? ` (${session.gitBranch})` : ''} |`);
  if (session.model) lines.push(`| Model | ${session.model} |`);
  if (session.startedAt) lines.push(`| Started | ${session.startedAt} |`);
  if (totals.wallMs != null) lines.push(`| Wall time | ${fmtMs(totals.wallMs)} |`);
  lines.push(`| Turns | ${totals.turns} |`);
  lines.push(`| Tool calls | ${totals.toolCalls}${totals.toolErrors ? ` (${totals.toolErrors} errors)` : ''} |`);
  lines.push(
    `| Tokens | in ${kTok(totals.tokens.input)} / out ${kTok(totals.tokens.output)} / ` +
      `cache-read ${kTok(totals.tokens.cacheRead)} / cache-write ${kTok(totals.tokens.cacheCreation)} |`
  );
  lines.push('');

  if (!flags.length) {
    lines.push('**No anomalies detected.** (That means the heuristics found nothing — not that nothing went wrong.)');
    return lines.join('\n');
  }

  lines.push(`## Anomalies (${flags.length})`);
  lines.push('');
  for (const f of flags) {
    const icon = f.severity === 'critical' ? '🟥' : '🟧';
    const range = f.turnStart === f.turnEnd ? `turn ${f.turnStart}` : `turns ${f.turnStart}–${f.turnEnd}`;
    lines.push(`### ${icon} ${f.title} — ${range}`);
    lines.push('');
    lines.push(f.detail);
    lines.push('');
    const evidence = evidenceFor(f, turns);
    if (evidence.length) {
      lines.push('```');
      lines.push(...evidence);
      lines.push('```');
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('_Generated by `agentfdr`. Open the timeline with `agentfdr open ' + (session.id ?? '').slice(0, 8) + '`._');
  return lines.join('\n');
}

function evidenceFor(flag, turns, max = 8) {
  const out = [];
  for (const t of turns) {
    if (t.index < flag.turnStart || t.index > flag.turnEnd) continue;
    for (const call of t.toolCalls) {
      const err = call.result?.isError ? '  [ERROR]' : '';
      out.push(`turn ${t.index}  ${call.name}(${call.summary})${err}`);
      if (out.length >= max) {
        out.push('…');
        return out;
      }
    }
  }
  return out;
}

export function fmtMs(ms) {
  if (ms == null) return '?';
  const s = Math.round(ms / 1000);
  if (s < 60) return `${s}s`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ${s % 60}s`;
  return `${Math.floor(m / 60)}h ${m % 60}m`;
}
